first_app/config/routes.rb
Rails.application.routes.draw do
  root  'users#index'  #この1行を追加

resources :boards do
  resources :comments, only: [:create, :destroy]
end
end

first_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

first_app/app/models/board.rb
class Board < ApplicationRecord
  has_many :comments, dependent: :destroy

  validates :title, presence: true, length: { in: 4..127 }
  validates :editor, presence: true, length: { in: 1..30 }
end

first_app/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :board

  validates :board, presence: true
  validates :name, presence: true
  validates :content, presence: true, length: { in: 1..1000 }
end

first_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

first_app/app/controllers/boards_controller.rb
class BoardsController < ApplicationController
 def index
   @boards = Board.all
  end

  def show
  @board = Board.includes(:comments).find(params[:id])
  @comment = Comment.new
  end

  def new
    @board = Board.new#追加した点　怖い 引数無しでもいい?
  end

  def create
    @board = Board.new(params_board)
    if @board.save
      redirect_to board_url(@board)
    else
      render "new"
    end
  end

  def edit
    @board = Board.find(params[:id])
  end

   def update
     @board = Board.find(params[:id])
     if @board.update_attributes(params_board)
       redirect_to board_url(@board)
     else
       render "edit"
     end
   end

  def destroy
  @board = Board.find(params[:id])
  @board.destroy
  redirect_to boards_url
  end

  private

  def params_board
    params.require(:board).permit(:title, :editor)
  end

end

first_app/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
  @board = Board.find(params[:board_id])
  @comment = Comment.new(params_comment)
  @comment.board = @board

  if @comment.save
    redirect_to board_url(@board)
  else
    render "boards/show"
  end
end

def destroy
 @board = Board.find(params[:board_id])
 @comment = Comment.find(params[:id])
 @comment.destroy
 redirect_to board_url(@board)
end

private

def params_comment
  params.require(:comment).permit(:name, :content)
end
end

first_app/app/helpers/application_helper.rb
module ApplicationHelper
end

first_app/app/views/boards/edit.html.erb
<%= link_to @board.title, board_path(@board) %>
<hr>
<% if @board.errors.any? %>
 <%= @board.errors.full_messages %>
<% end %>
<h1>Boards#edit</h1>
<%= form_for @board do |f| %>
  タイトル: <%= f.text_field :title %> <br>
  作成者名: <%= f.text_field :editor %> <br>
  <%= f.submit %>
<% end %>

first_app/app/views/boards/index.html.erb
<div class="wrapper wrapper__bg">
 <div class="container">
    <h1>掲示板</h1>
   <%= link_to "スレッド新規作成", new_board_path %>
   <hr>
      <div class="panel">
     <% @boards.each do |board| %>
     <%= link_to board.title, board_path(board) %> </br>
     <% end %>
    </div>
  </div>
</div>

first_app/app/views/boards/new.html.erb
<%= link_to "スレッド一覧に戻る", boards_path %>
<hr>
<h1>Boards#new</h1>
<% if @board.errors.any? %>
  <%= @board.errors.full_messages %>
<% end %>
<%= form_for @board do |f| %>
 タイトル: <%= f.text_field :title %> <br>
 作成者名: <%= f.text_field :editor %> <br>
 <%= f.submit %>
<% end %>

first_app/app/views/boards/show.html.erb
<div class="wrapper wrapper__bg">
 <div class="container">
 <%= link_to "スレッド一覧に戻る", boards_path %>
 <hr>
 <div class="board">
 <h1 class="board--name"><%= @board.title %></h1>
 </div>
 <%= link_to "タイトルを編集する", edit_board_path(@board) %>
 <%= link_to "削除する", board_path(@board), method: :delete, data: { confirm: "本当に削除しますか？" } %>
 <hr>
 <div class="comments">
<% @board.comments.each do |comment| %>
  <%= comment.name %>
  <%= comment.content %>
  <%= link_to "削除する", board_comment_path(@board, comment), method: :delete, data: { confirm: "本当に削除しますか?" } %> <br>
<% end %>
</div>
<hr>
 <%= form_for @comment, url: board_comments_path(@board, @comment) do |f| %>
 名前: <%= f.text_field :name %> <br>
 コメント: <%= f.text_area :content %> <br>
 <%= f.submit %>
 <% end %>
 </div>
</div>

first_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>